/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package aws.lambda.terraform.java.play

class App {
    String getGreeting() {
        return 'Hello World!'
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
